
server.port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/academia
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace